---
apiVersion: v1
kind: Service
metadata:
  name: multipaper-leader
spec:
  ports:
    - name: server
      port: 35353
      targetPort: server
      protocol: TCP
    - name: proxy
      port: 25565
      targetPort: proxy
  type: LoadBalancer
  selector:
    app: multipaper-leader
